// <auto-generated />
using System;
using Article.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Article.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240824191137_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Article.Api.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastUpdate = new DateTime(2024, 8, 24, 22, 11, 37, 29, DateTimeKind.Local).AddTicks(1061),
                            Title = "Article 1",
                            WriterId = 1
                        },
                        new
                        {
                            Id = 2,
                            LastUpdate = new DateTime(2024, 8, 24, 22, 11, 37, 29, DateTimeKind.Local).AddTicks(1073),
                            Title = "Article 2",
                            WriterId = 2
                        },
                        new
                        {
                            Id = 3,
                            LastUpdate = new DateTime(2024, 8, 24, 22, 11, 37, 29, DateTimeKind.Local).AddTicks(1075),
                            Title = "Article 3",
                            WriterId = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
